package com.wanandroid.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wanandroid.logic.login.moudle.LogicGreenDaoBean;
import com.wanandroid.logic.search.moudle.SearchGreenDaoBean;

import com.wanandroid.greendao.LogicGreenDaoBeanDao;
import com.wanandroid.greendao.SearchGreenDaoBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig logicGreenDaoBeanDaoConfig;
    private final DaoConfig searchGreenDaoBeanDaoConfig;

    private final LogicGreenDaoBeanDao logicGreenDaoBeanDao;
    private final SearchGreenDaoBeanDao searchGreenDaoBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        logicGreenDaoBeanDaoConfig = daoConfigMap.get(LogicGreenDaoBeanDao.class).clone();
        logicGreenDaoBeanDaoConfig.initIdentityScope(type);

        searchGreenDaoBeanDaoConfig = daoConfigMap.get(SearchGreenDaoBeanDao.class).clone();
        searchGreenDaoBeanDaoConfig.initIdentityScope(type);

        logicGreenDaoBeanDao = new LogicGreenDaoBeanDao(logicGreenDaoBeanDaoConfig, this);
        searchGreenDaoBeanDao = new SearchGreenDaoBeanDao(searchGreenDaoBeanDaoConfig, this);

        registerDao(LogicGreenDaoBean.class, logicGreenDaoBeanDao);
        registerDao(SearchGreenDaoBean.class, searchGreenDaoBeanDao);
    }
    
    public void clear() {
        logicGreenDaoBeanDaoConfig.clearIdentityScope();
        searchGreenDaoBeanDaoConfig.clearIdentityScope();
    }

    public LogicGreenDaoBeanDao getLogicGreenDaoBeanDao() {
        return logicGreenDaoBeanDao;
    }

    public SearchGreenDaoBeanDao getSearchGreenDaoBeanDao() {
        return searchGreenDaoBeanDao;
    }

}
